### ISSUE TITLE
出现Error building site错误

### ISSUE THREAD

**Issue by WangRongsheng** [zhengzangw/hugo-site#1]
当我执行hugo serve后出现了以下错误：
Error: Error building site: TOCSS: failed to transform "sass/main.scss" (text/x-scss): resource "scss/sass/main.scss_c7d65b6eceb0fea0354886e96cfa417e" not found in file cache

我该怎么样去解决我的问题呢

**Comment by zhengzangw** [comment]
该 repository 为个人站点，非主题目录。若想使用相同主题，请查看 https://github.com/zhengzangw/hugo-theme-ztyblog
若还遇到相同问题，请在该主题 issue 区提问
